name: fuzzy_string
description: A starting point for Dart libraries or applications.
version: 0.1.0
repository: https://github.com/ross96D/fuzzy_string

environment:
  sdk: ">=3.0.0"

dependencies:

dev_dependencies:
  test: ^1.16.0
