name: fuzzy_string
description: A package implementing some fuzzy string matching algorithms.
version: 1.0.0
repository: https://github.com/ross96D/fuzzy_string

environment:
  sdk: ">=3.0.0"

dependencies:

dev_dependencies:
  test: ^1.16.0
